// everything from our tailwind config, except `plugins` utilities
export default {
  theme: {
    borderColor: {
      color: {
        1: "var(--calcite-ui-border-1)",
        2: "var(--calcite-ui-border-2)",
        3: "var(--calcite-ui-border-3)",
        input: "var(--calcite-ui-border-input)"
      },
      "color-brand": "var(--calcite-ui-brand)",
      "color-brand-hover": "var(--calcite-ui-brand-hover)",
      "color-brand-press": "var(--calcite-ui-brand-press)",
      "color-info": "var(--calcite-ui-info)",
      "color-success": "var(--calcite-ui-success)",
      "color-warning": "var(--calcite-ui-warning)",
      "color-danger": "var(--calcite-ui-danger)",
      "color-danger-hover": "var(--calcite-ui-danger-hover)",
      "color-danger-press": "var(--calcite-ui-danger-press)"
    },
    colors: {
      brand: "var(--calcite-ui-brand)",
      "brand-hover": "var(--calcite-ui-brand-hover)",
      "brand-press": "var(--calcite-ui-brand-press)",
      info: "var(--calcite-ui-info)",
      success: "var(--calcite-ui-success)",
      warning: "var(--calcite-ui-warning)",
      danger: "var(--calcite-ui-danger)",
      "danger-hover": "var(--calcite-ui-danger-hover)",
      "danger-press": "var(--calcite-ui-danger-press)",
      background: {
        background: "var(--calcite-ui-background)",
        foreground: {
          "1": "var(--calcite-ui-foreground-1)",
          "2": "var(--calcite-ui-foreground-2)",
          "3": "var(--calcite-ui-foreground-3)"
        }
      },
      text: {
        "1": "var(--calcite-ui-text-1)",
        "2": "var(--calcite-ui-text-2)",
        "3": "var(--calcite-ui-text-3)",
        inverse: "var(--calcite-ui-text-inverse)",
        link: "var(--calcite-ui-text-link)"
      },
      transparent: "transparent"
    },
    fontFamily: {
      sans: "var(--calcite-sans-family)",
      mono: "var(--calcite-code-family)",
      inherit: "inherit"
    },
    fontSize: {
      "0": "var(--calcite-font-size-0)",
      "0-wrap": ["var(--calcite-font-size-0)", { lineHeight: "1.375" }],
      "1": "var(--calcite-font-size-1)",
      "1-wrap": ["var(--calcite-font-size-1)", { lineHeight: "1.375" }],
      "2": "var(--calcite-font-size-2)",
      "2-wrap": ["var(--calcite-font-size-2)", { lineHeight: "1.375" }],
      "3": "var(--calcite-font-size-3)",
      "3-wrap": ["var(--calcite-font-size-3)", { lineHeight: "1.25" }],
      "4": "var(--calcite-font-size-4)",
      "4-wrap": ["var(--calcite-font-size-4)", { lineHeight: "1.25" }],
      "5": "var(--calcite-font-size-5)",
      "5-wrap": ["var(--calcite-font-size-5)", { lineHeight: "1.25" }],
      "6": "var(--calcite-font-size-6)",
      "6-wrap": ["var(--calcite-font-size-6)", { lineHeight: "1.25" }],
      "7": "var(--calcite-font-size-7)",
      "7-wrap": ["var(--calcite-font-size-7)", { lineHeight: "1.25" }],
      "8": "var(--calcite-font-size-8)",
      "8-wrap": ["var(--calcite-font-size-8)", { lineHeight: "1.25" }],
      "-3": "var(--calcite-font-size--3)",
      "-3-wrap": ["var(--calcite-font-size--3)", { lineHeight: "1.375" }],
      "-2": "var(--calcite-font-size--2)",
      "-2-wrap": ["var(--calcite-font-size--2)", { lineHeight: "1.375" }],
      "-1": "var(--calcite-font-size--1)",
      "-1-wrap": ["var(--calcite-font-size--1)", { lineHeight: "1.375" }],
      "-3h": ["var(--calcite-font-size--3)", { lineHeight: "0.75rem" }],
      "-2h": ["var(--calcite-font-size--2)", { lineHeight: "1rem" }],
      "-1h": ["var(--calcite-font-size--1)", { lineHeight: "1rem" }],
      "0h": ["var(--calcite-font-size-0)", { lineHeight: "1.25rem" }],
      "1h": ["var(--calcite-font-size-1)", { lineHeight: "1.5rem" }],
      "2h": ["var(--calcite-font-size-2)", { lineHeight: "1.5rem" }],
      "3h": ["var(--calcite-font-size-3)", { lineHeight: "2rem" }],
      "4h": ["var(--calcite-font-size-4)", { lineHeight: "2.5rem" }],
      "5h": ["var(--calcite-font-size-5)", { lineHeight: "3rem" }],
      "6h": ["var(--calcite-font-size-6)", { lineHeight: "4rem" }],
      "7h": ["var(--calcite-font-size-7)", { lineHeight: "4rem" }],
      "8h": ["var(--calcite-font-size-8)", { lineHeight: "5rem" }]
    },
    fontWeight: {
      light: "var(--calcite-font-weight-light)",
      normal: "var(--calcite-font-weight-normal)",
      medium: "var(--calcite-font-weight-medium)",
      bold: "var(--calcite-font-weight-bold)"
    },
    screens: { s: "480px", m: "864px", l: "1024px", xl: "1440px" },
    textColor: {
      color: {
        "1": "var(--calcite-ui-text-1)",
        "2": "var(--calcite-ui-text-2)",
        "3": "var(--calcite-ui-text-3)",
        inverse: "var(--calcite-ui-text-inverse)",
        link: "var(--calcite-ui-text-link)"
      }
    },
    backgroundColor: {
      background: "var(--calcite-ui-background)",
      foreground: {
        "1": "var(--calcite-ui-foreground-1)",
        "2": "var(--calcite-ui-foreground-2)",
        "3": "var(--calcite-ui-foreground-3)"
      },
      transparent: "transparent",
      "brand-hover": "var(--calcite-ui-brand-hover)",
      "brand-press": "var(--calcite-ui-brand-press)",
      brand: "var(--calcite-ui-brand)",
      info: "var(--calcite-ui-info)",
      success: "var(--calcite-ui-success)",
      warning: "var(--calcite-ui-warning)",
      danger: "var(--calcite-ui-danger)",
      "danger-hover": "var(--calcite-ui-danger-hover)",
      "danger-press": "var(--calcite-ui-danger-press)"
    },
    spacing: {
      "0": "0",
      "1": "0.25rem",
      "2": "0.5rem",
      "3": "0.75rem",
      "4": "1rem",
      "5": "1.25rem",
      "6": "1.5rem",
      "8": "2rem",
      "10": "2.5rem",
      "12": "3rem",
      "16": "4rem",
      "20": "5rem",
      "24": "6rem",
      "32": "8rem",
      "40": "10rem",
      "48": "12rem",
      "56": "14rem",
      "64": "16rem",
      px: "1px",
      "0.5": "0.125rem",
      "2.5": "0.625rem",
      "3.5": "0.875rem"
    },
    backgroundImage: {
      none: "none",
      "gradient-to-t": "linear-gradient(to top, var(--gradient-color-stops))",
      "gradient-to-tr": "linear-gradient(to top right, var(--gradient-color-stops))",
      "gradient-to-r": "linear-gradient(to right, var(--gradient-color-stops))",
      "gradient-to-br": "linear-gradient(to bottom right, var(--gradient-color-stops))",
      "gradient-to-b": "linear-gradient(to bottom, var(--gradient-color-stops))",
      "gradient-to-bl": "linear-gradient(to bottom left, var(--gradient-color-stops))",
      "gradient-to-l": "linear-gradient(to left, var(--gradient-color-stops))",
      "gradient-to-tl": "linear-gradient(to top left, var(--gradient-color-stops))"
    },
    gradientColorStops: {
      brand: "var(--calcite-ui-brand)",
      "brand-hover": "var(--calcite-ui-brand-hover)",
      "brand-press": "var(--calcite-ui-brand-press)",
      info: "var(--calcite-ui-info)",
      success: "var(--calcite-ui-success)",
      warning: "var(--calcite-ui-warning)",
      danger: "var(--calcite-ui-danger)",
      "danger-hover": "var(--calcite-ui-danger-hover)",
      "danger-press": "var(--calcite-ui-danger-press)",
      background: {
        background: "var(--calcite-ui-background)",
        foreground: {
          "1": "var(--calcite-ui-foreground-1)",
          "2": "var(--calcite-ui-foreground-2)",
          "3": "var(--calcite-ui-foreground-3)"
        }
      },
      text: {
        "1": "var(--calcite-ui-text-1)",
        "2": "var(--calcite-ui-text-2)",
        "3": "var(--calcite-ui-text-3)",
        inverse: "var(--calcite-ui-text-inverse)",
        link: "var(--calcite-ui-text-link)"
      },
      transparent: "transparent"
    },
    backgroundOpacity: {
      "0": "0",
      "25": "0.25",
      "50": "0.5",
      "75": "0.75",
      "100": "1",
      disabled: "0.5"
    },
    backgroundPosition: {
      bottom: "bottom",
      center: "center",
      left: "left",
      "left-bottom": "left bottom",
      "left-top": "left top",
      right: "right",
      "right-bottom": "right bottom",
      "right-top": "right top",
      top: "top"
    },
    backgroundSize: { auto: "auto", cover: "cover", contain: "contain" },
    borderOpacity: {
      "0": "0",
      "25": "0.25",
      "50": "0.5",
      "75": "0.75",
      "100": "1",
      disabled: "0.5"
    },
    borderRadius: {
      none: "0",
      sm: "0.125rem",
      default: "0.25rem",
      md: "0.375rem",
      lg: "0.5rem",
      xl: "0.75rem",
      "2xl": "1rem",
      "3xl": "1.5rem",
      full: "9999px",
      half: "50%"
    },
    borderWidth: { "0": "0", "2": "2px", "4": "4px", "8": "8px", default: "1px" },
    boxShadow: {
      "0": "0 4px 8px -1px rgba(0, 0, 0, 0.08), 0 2px 4px -1px rgba(0, 0, 0, 0.04)",
      "1": "0 4px 8px -1px rgba(0, 0, 0, 0.08), 0 2px 4px -1px rgba(0, 0, 0, 0.04)",
      "2": "0 6px 20px -4px rgba(0, 0, 0, 0.1), 0 4px 12px -2px rgba(0, 0, 0, 0.08)",
      xs: "0 0 0 1px rgba(0, 0, 0, 0.05)",
      sm: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
      default: "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)",
      md: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
      lg: "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
      xl: "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
      "2xl": "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
      inner: "inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)",
      outline: "0 0 0 3px rgba(66, 153, 225, 0.5)",
      none: "none",
      "1-lg": "0 4px 16px 0 rgba(0, 0, 0, 0.08), 0 2px 8px 0 rgba(0, 0, 0, 0.04)",
      "1-sm": "0 1px 6px -1px rgba(0, 0, 0, 0.16), 0 1px 2px -1px rgba(0, 0, 0, 0.08)",
      "2-lg": "0 12px 32px -2px rgba(0, 0, 0, 0.1), 0 4px 20px 0 rgba(0, 0, 0, 0.08)",
      "2-sm": "0 2px 12px -4px rgba(0, 0, 0, 0.2), 0 2px 4px -2px rgba(0, 0, 0, 0.16)",
      "border-bottom": "0 1px 0 var(--calcite-ui-border-3)",
      "outline-active": "0 0 0 1px var(--calcite-ui-brand)"
    },
    container: {},
    cursor: {
      auto: "auto",
      default: "default",
      pointer: "pointer",
      wait: "wait",
      text: "text",
      move: "move",
      "not-allowed": "not-allowed"
    },
    divideColor: {
      color: {
        "1": "var(--calcite-ui-border-1)",
        "2": "var(--calcite-ui-border-2)",
        "3": "var(--calcite-ui-border-3)",
        input: "var(--calcite-ui-border-input)"
      },
      "color-brand": "var(--calcite-ui-brand)",
      "color-brand-hover": "var(--calcite-ui-brand-hover)",
      "color-brand-press": "var(--calcite-ui-brand-press)",
      "color-info": "var(--calcite-ui-info)",
      "color-success": "var(--calcite-ui-success)",
      "color-warning": "var(--calcite-ui-warning)",
      "color-danger": "var(--calcite-ui-danger)",
      "color-danger-hover": "var(--calcite-ui-danger-hover)",
      "color-danger-press": "var(--calcite-ui-danger-press)"
    },
    divideOpacity: {
      "0": "0",
      "25": "0.25",
      "50": "0.5",
      "75": "0.75",
      "100": "1",
      disabled: "0.5"
    },
    divideWidth: { "0": "0", "2": "2px", "4": "4px", "8": "8px", default: "1px" },
    fill: {
      current: "currentColor",
      color: {
        "1": "var(--calcite-ui-text-1)",
        "2": "var(--calcite-ui-text-2)",
        "3": "var(--calcite-ui-text-3)",
        inverse: "var(--calcite-ui-text-inverse)",
        link: "var(--calcite-ui-text-link)"
      }
    },
    flex: {
      "1": "1 1 0%",
      auto: "1 1 auto",
      initial: "0 1 auto",
      none: "none"
    },
    flexGrow: { "0": "0", default: "1" },
    flexShrink: { "0": "0", default: "1" },
    height: {
      "0": "0",
      "1": "0.25rem",
      "2": "0.5rem",
      "3": "0.75rem",
      "4": "1rem",
      "5": "1.25rem",
      "6": "1.5rem",
      "8": "2rem",
      "10": "2.5rem",
      "12": "3rem",
      "16": "4rem",
      "20": "5rem",
      "24": "6rem",
      "32": "8rem",
      "40": "10rem",
      "48": "12rem",
      "56": "14rem",
      "64": "16rem",
      auto: "auto",
      px: "1px",
      "0.5": "0.125rem",
      "2.5": "0.625rem",
      "3.5": "0.875rem",
      full: "100%",
      screen: "100vh"
    },
    inset: { "0": "0", auto: "auto" },
    letterSpacing: {
      tighter: "-0.05em",
      tight: "-0.025em",
      normal: "0",
      wide: "0.025em",
      wider: "0.05em",
      widest: "0.1em"
    },
    lineHeight: {
      "3": ".75rem",
      "4": "1rem",
      "5": "1.25rem",
      "6": "1.5rem",
      "7": "1.75rem",
      "8": "2rem",
      "9": "2.25rem",
      "10": "2.5rem",
      none: "1",
      tight: "1.25",
      snug: "1.375",
      normal: "1.5",
      relaxed: "1.625",
      loose: "2"
    },
    listStyleType: { none: "none", disc: "disc", decimal: "decimal" },
    margin: {
      "0": "0",
      "1": "0.25rem",
      "2": "0.5rem",
      "3": "0.75rem",
      "4": "1rem",
      "5": "1.25rem",
      "6": "1.5rem",
      "8": "2rem",
      "10": "2.5rem",
      "12": "3rem",
      "16": "4rem",
      "20": "5rem",
      "24": "6rem",
      "32": "8rem",
      "40": "10rem",
      "48": "12rem",
      "56": "14rem",
      "64": "16rem",
      auto: "auto",
      px: "1px",
      "0.5": "0.125rem",
      "2.5": "0.625rem",
      "3.5": "0.875rem",
      "-1": "-0.25rem",
      "-2": "-0.5rem",
      "-3": "-0.75rem",
      "-4": "-1rem",
      "-5": "-1.25rem",
      "-6": "-1.5rem",
      "-8": "-2rem",
      "-10": "-2.5rem",
      "-12": "-3rem",
      "-16": "-4rem",
      "-20": "-5rem",
      "-24": "-6rem",
      "-32": "-8rem",
      "-40": "-10rem",
      "-48": "-12rem",
      "-56": "-14rem",
      "-64": "-16rem",
      "-px": "-1px",
      "-0.5": "-0.125rem",
      "-2.5": "-0.625rem",
      "-3.5": "-0.875rem"
    },
    maxHeight: { full: "100%", screen: "100vh" },
    maxWidth: {
      none: "none",
      xs: "20rem",
      sm: "24rem",
      md: "28rem",
      lg: "32rem",
      xl: "36rem",
      "2xl": "42rem",
      "3xl": "48rem",
      "4xl": "56rem",
      "5xl": "64rem",
      "6xl": "72rem",
      full: "100%",
      "screen-s": "480px",
      "screen-m": "864px",
      "screen-l": "1024px",
      "screen-xl": "1440px"
    },
    minHeight: { "0": "0", full: "100%", screen: "100vh" },
    minWidth: { "0": "0", full: "100%" },
    objectPosition: {
      bottom: "bottom",
      center: "center",
      left: "left",
      "left-bottom": "left bottom",
      "left-top": "left top",
      right: "right",
      "right-bottom": "right bottom",
      "right-top": "right top",
      top: "top"
    },
    opacity: {
      "0": "0",
      "25": "0.25",
      "50": "0.5",
      "75": "0.75",
      "100": "1",
      disabled: "0.5"
    },
    order: {
      "1": "1",
      "2": "2",
      "3": "3",
      "4": "4",
      "5": "5",
      "6": "6",
      "7": "7",
      "8": "8",
      "9": "9",
      "10": "10",
      "11": "11",
      "12": "12",
      first: "-9999",
      last: "9999",
      none: "0"
    },
    outline: {
      none: ["2px solid transparent", "2px"],
      white: ["2px dotted white", "2px"],
      black: ["2px dotted black", "2px"]
    },
    padding: {
      "0": "0",
      "1": "0.25rem",
      "2": "0.5rem",
      "3": "0.75rem",
      "4": "1rem",
      "5": "1.25rem",
      "6": "1.5rem",
      "8": "2rem",
      "10": "2.5rem",
      "12": "3rem",
      "16": "4rem",
      "20": "5rem",
      "24": "6rem",
      "32": "8rem",
      "40": "10rem",
      "48": "12rem",
      "56": "14rem",
      "64": "16rem",
      px: "1px",
      "0.5": "0.125rem",
      "2.5": "0.625rem",
      "3.5": "0.875rem"
    },
    placeholderColor: {
      brand: "var(--calcite-ui-brand)",
      "brand-hover": "var(--calcite-ui-brand-hover)",
      "brand-press": "var(--calcite-ui-brand-press)",
      info: "var(--calcite-ui-info)",
      success: "var(--calcite-ui-success)",
      warning: "var(--calcite-ui-warning)",
      danger: "var(--calcite-ui-danger)",
      "danger-hover": "var(--calcite-ui-danger-hover)",
      "danger-press": "var(--calcite-ui-danger-press)",
      background: {
        background: "var(--calcite-ui-background)",
        foreground: {
          "1": "var(--calcite-ui-foreground-1)",
          "2": "var(--calcite-ui-foreground-2)",
          "3": "var(--calcite-ui-foreground-3)"
        }
      },
      text: {
        "1": "var(--calcite-ui-text-1)",
        "2": "var(--calcite-ui-text-2)",
        "3": "var(--calcite-ui-text-3)",
        inverse: "var(--calcite-ui-text-inverse)",
        link: "var(--calcite-ui-text-link)"
      },
      transparent: "transparent"
    },
    placeholderOpacity: {
      "0": "0",
      "25": "0.25",
      "50": "0.5",
      "75": "0.75",
      "100": "1",
      disabled: "0.5"
    },
    space: {
      "0": "0",
      "1": "0.25rem",
      "2": "0.5rem",
      "3": "0.75rem",
      "4": "1rem",
      "5": "1.25rem",
      "6": "1.5rem",
      "8": "2rem",
      "10": "2.5rem",
      "12": "3rem",
      "16": "4rem",
      "20": "5rem",
      "24": "6rem",
      "32": "8rem",
      "40": "10rem",
      "48": "12rem",
      "56": "14rem",
      "64": "16rem",
      px: "1px",
      "0.5": "0.125rem",
      "2.5": "0.625rem",
      "3.5": "0.875rem",
      "-1": "-0.25rem",
      "-2": "-0.5rem",
      "-3": "-0.75rem",
      "-4": "-1rem",
      "-5": "-1.25rem",
      "-6": "-1.5rem",
      "-8": "-2rem",
      "-10": "-2.5rem",
      "-12": "-3rem",
      "-16": "-4rem",
      "-20": "-5rem",
      "-24": "-6rem",
      "-32": "-8rem",
      "-40": "-10rem",
      "-48": "-12rem",
      "-56": "-14rem",
      "-64": "-16rem",
      "-px": "-1px",
      "-0.5": "-0.125rem",
      "-2.5": "-0.625rem",
      "-3.5": "-0.875rem"
    },
    stroke: { current: "currentColor" },
    strokeWidth: { "0": "0", "1": "1", "2": "2" },
    textOpacity: {
      "0": "0",
      "25": "0.25",
      "50": "0.5",
      "75": "0.75",
      "100": "1",
      disabled: "0.5"
    },
    width: {
      "0": "0",
      "1": "0.25rem",
      "2": "0.5rem",
      "3": "0.75rem",
      "4": "1rem",
      "5": "1.25rem",
      "6": "1.5rem",
      "8": "2rem",
      "10": "2.5rem",
      "12": "3rem",
      "16": "4rem",
      "20": "5rem",
      "24": "6rem",
      "32": "8rem",
      "40": "10rem",
      "48": "12rem",
      "56": "14rem",
      "64": "16rem",
      auto: "auto",
      px: "1px",
      "0.5": "0.125rem",
      "2.5": "0.625rem",
      "3.5": "0.875rem",
      "1/2": "50%",
      "1/3": "33.333333%",
      "2/3": "66.666667%",
      "1/4": "25%",
      "2/4": "50%",
      "3/4": "75%",
      "1/5": "20%",
      "2/5": "40%",
      "3/5": "60%",
      "4/5": "80%",
      "1/6": "16.666667%",
      "2/6": "33.333333%",
      "3/6": "50%",
      "4/6": "66.666667%",
      "5/6": "83.333333%",
      "1/12": "8.333333%",
      "2/12": "16.666667%",
      "3/12": "25%",
      "4/12": "33.333333%",
      "5/12": "41.666667%",
      "6/12": "50%",
      "7/12": "58.333333%",
      "8/12": "66.666667%",
      "9/12": "75%",
      "10/12": "83.333333%",
      "11/12": "91.666667%",
      full: "100%",
      screen: "100vw"
    },
    zIndex: {
      "0": "0",
      "10": "10",
      "20": "20",
      "30": "30",
      "40": "40",
      "50": "50",
      auto: "auto"
    },
    gap: {
      "0": "0",
      "1": "0.25rem",
      "2": "0.5rem",
      "3": "0.75rem",
      "4": "1rem",
      "5": "1.25rem",
      "6": "1.5rem",
      "8": "2rem",
      "10": "2.5rem",
      "12": "3rem",
      "16": "4rem",
      "20": "5rem",
      "24": "6rem",
      "32": "8rem",
      "40": "10rem",
      "48": "12rem",
      "56": "14rem",
      "64": "16rem",
      px: "1px",
      "0.5": "0.125rem",
      "2.5": "0.625rem",
      "3.5": "0.875rem"
    },
    gridTemplateColumns: {
      "1": "repeat(1, minmax(0, 1fr))",
      "2": "repeat(2, minmax(0, 1fr))",
      "3": "repeat(3, minmax(0, 1fr))",
      "4": "repeat(4, minmax(0, 1fr))",
      "5": "repeat(5, minmax(0, 1fr))",
      "6": "repeat(6, minmax(0, 1fr))",
      "7": "repeat(7, minmax(0, 1fr))",
      "8": "repeat(8, minmax(0, 1fr))",
      "9": "repeat(9, minmax(0, 1fr))",
      "10": "repeat(10, minmax(0, 1fr))",
      "11": "repeat(11, minmax(0, 1fr))",
      "12": "repeat(12, minmax(0, 1fr))",
      none: "none"
    },
    gridAutoColumns: {
      auto: "auto",
      min: "min-content",
      max: "max-content",
      fr: "minmax(0, 1fr)"
    },
    gridColumn: {
      auto: "auto",
      "span-1": "span 1 / span 1",
      "span-2": "span 2 / span 2",
      "span-3": "span 3 / span 3",
      "span-4": "span 4 / span 4",
      "span-5": "span 5 / span 5",
      "span-6": "span 6 / span 6",
      "span-7": "span 7 / span 7",
      "span-8": "span 8 / span 8",
      "span-9": "span 9 / span 9",
      "span-10": "span 10 / span 10",
      "span-11": "span 11 / span 11",
      "span-12": "span 12 / span 12",
      "span-full": "1 / -1"
    },
    gridColumnStart: {
      "1": "1",
      "2": "2",
      "3": "3",
      "4": "4",
      "5": "5",
      "6": "6",
      "7": "7",
      "8": "8",
      "9": "9",
      "10": "10",
      "11": "11",
      "12": "12",
      "13": "13",
      auto: "auto"
    },
    gridColumnEnd: {
      "1": "1",
      "2": "2",
      "3": "3",
      "4": "4",
      "5": "5",
      "6": "6",
      "7": "7",
      "8": "8",
      "9": "9",
      "10": "10",
      "11": "11",
      "12": "12",
      "13": "13",
      auto: "auto"
    },
    gridTemplateRows: {
      "1": "repeat(1, minmax(0, 1fr))",
      "2": "repeat(2, minmax(0, 1fr))",
      "3": "repeat(3, minmax(0, 1fr))",
      "4": "repeat(4, minmax(0, 1fr))",
      "5": "repeat(5, minmax(0, 1fr))",
      "6": "repeat(6, minmax(0, 1fr))",
      none: "none"
    },
    gridAutoRows: {
      auto: "auto",
      min: "min-content",
      max: "max-content",
      fr: "minmax(0, 1fr)"
    },
    gridRow: {
      auto: "auto",
      "span-1": "span 1 / span 1",
      "span-2": "span 2 / span 2",
      "span-3": "span 3 / span 3",
      "span-4": "span 4 / span 4",
      "span-5": "span 5 / span 5",
      "span-6": "span 6 / span 6",
      "span-full": "1 / -1"
    },
    gridRowStart: {
      "1": "1",
      "2": "2",
      "3": "3",
      "4": "4",
      "5": "5",
      "6": "6",
      "7": "7",
      auto: "auto"
    },
    gridRowEnd: {
      "1": "1",
      "2": "2",
      "3": "3",
      "4": "4",
      "5": "5",
      "6": "6",
      "7": "7",
      auto: "auto"
    },
    transformOrigin: {
      center: "center",
      top: "top",
      "top-right": "top right",
      right: "right",
      "bottom-right": "bottom right",
      bottom: "bottom",
      "bottom-left": "bottom left",
      left: "left",
      "top-left": "top left"
    },
    scale: {
      "0": "0",
      "50": ".5",
      "75": ".75",
      "90": ".9",
      "95": ".95",
      "100": "1",
      "105": "1.05",
      "110": "1.1",
      "125": "1.25",
      "150": "1.5"
    },
    rotate: {
      "0": "0",
      "1": "1deg",
      "2": "2deg",
      "3": "3deg",
      "6": "6deg",
      "12": "12deg",
      "45": "45deg",
      "90": "90deg",
      "180": "180deg",
      "-180": "-180deg",
      "-90": "-90deg",
      "-45": "-45deg",
      "-12": "-12deg",
      "-6": "-6deg",
      "-3": "-3deg",
      "-2": "-2deg",
      "-1": "-1deg"
    },
    translate: {
      "0": "0",
      "1": "0.25rem",
      "2": "0.5rem",
      "3": "0.75rem",
      "4": "1rem",
      "5": "1.25rem",
      "6": "1.5rem",
      "8": "2rem",
      "10": "2.5rem",
      "12": "3rem",
      "16": "4rem",
      "20": "5rem",
      "24": "6rem",
      "32": "8rem",
      "40": "10rem",
      "48": "12rem",
      "56": "14rem",
      "64": "16rem",
      px: "1px",
      "0.5": "0.125rem",
      "2.5": "0.625rem",
      "3.5": "0.875rem",
      "-1": "-0.25rem",
      "-2": "-0.5rem",
      "-3": "-0.75rem",
      "-4": "-1rem",
      "-5": "-1.25rem",
      "-6": "-1.5rem",
      "-8": "-2rem",
      "-10": "-2.5rem",
      "-12": "-3rem",
      "-16": "-4rem",
      "-20": "-5rem",
      "-24": "-6rem",
      "-32": "-8rem",
      "-40": "-10rem",
      "-48": "-12rem",
      "-56": "-14rem",
      "-64": "-16rem",
      "-px": "-1px",
      "-0.5": "-0.125rem",
      "-2.5": "-0.625rem",
      "-3.5": "-0.875rem",
      "-full": "-100%",
      "-1/2": "-50%",
      "1/2": "50%",
      full: "100%"
    },
    skew: {
      "0": "0",
      "1": "1deg",
      "2": "2deg",
      "3": "3deg",
      "6": "6deg",
      "12": "12deg",
      "-12": "-12deg",
      "-6": "-6deg",
      "-3": "-3deg",
      "-2": "-2deg",
      "-1": "-1deg"
    },
    transitionProperty: {
      none: "none",
      all: "all",
      default: "background-color, border-color, color, fill, stroke, opacity, box-shadow, transform",
      colors: "background-color, border-color, color, fill, stroke",
      opacity: "opacity",
      shadow: "box-shadow",
      transform: "transform",
      margin: "margin",
      color: "color"
    },
    transitionTimingFunction: {
      linear: "linear",
      in: "cubic-bezier(0.4, 0, 1, 1)",
      out: "cubic-bezier(0, 0, 0.2, 1)",
      "in-out": "cubic-bezier(0.4, 0, 0.2, 1)",
      cubic: "cubic-bezier(0.215, 0.440, 0.420, 0.880)"
    },
    transitionDuration: {
      "75": "75ms",
      "100": "100ms",
      "150": "150ms",
      "200": "200ms",
      "300": "300ms",
      "500": "500ms",
      "700": "700ms",
      "1000": "1000ms"
    },
    transitionDelay: {
      "75": "75ms",
      "100": "100ms",
      "150": "150ms",
      "200": "200ms",
      "300": "300ms",
      "500": "500ms",
      "700": "700ms",
      "1000": "1000ms"
    },
    animation: {
      none: "none",
      spin: "spin 1s linear infinite",
      ping: "ping 1s cubic-bezier(0, 0, 0.2, 1) infinite",
      pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      bounce: "bounce 1s infinite",
      in: "in 300ms ease-in-out",
      "in-down": "in-down 300ms ease-in-out",
      "in-up": "in-up 300ms ease-in-out",
      "in-scale": "in-scale 300ms linear"
    },
    keyframes: {
      spin: { to: { transform: "rotate(360deg)" } },
      ping: { "75%, 100%": { opacity: "0", transform: "scale(2)" } },
      pulse: { "50%": { opacity: ".5" } },
      bounce: {
        "0%, 100%": { animationTimingFunction: "cubic-bezier(0.8,0,1,1)", transform: "translateY(-25%)" },
        "50%": { animationTimingFunction: "cubic-bezier(0,0,0.2,1)", transform: "none" }
      },
      in: { "0%": { opacity: 0 }, "100%": { opacity: 1 } },
      "in-down": {
        "0%": { opacity: 0, transform: "translate3D(0, -5px, 0)" },
        "100%": { opacity: 1, transform: "translate3D(0, 0, 0)" }
      },
      "in-up": {
        "0%": { opacity: 0, transform: "translate3D(0, 5px, 0)" },
        "100%": { opacity: 1, transform: "translate3D(0, 0, 0)" }
      },
      "in-scale": {
        "0%": { opacity: 0, transform: "scale3D(0.95, 0.95, 1)" },
        "100%": { opacity: 1, transform: "scale3D(1, 1, 1)" }
      }
    }
  },
  variants: {
    accessibility: ["responsive", "focus"],
    alignContent: ["responsive"],
    alignItems: ["responsive"],
    alignSelf: ["responsive"],
    appearance: ["responsive"],
    backgroundAttachment: ["responsive"],
    backgroundClip: ["responsive"],
    backgroundColor: ["responsive", "hover", "focus"],
    backgroundImage: ["responsive"],
    gradientColorStops: ["responsive", "hover", "focus"],
    backgroundOpacity: ["responsive", "hover", "focus"],
    backgroundPosition: ["responsive"],
    backgroundRepeat: ["responsive"],
    backgroundSize: ["responsive"],
    borderCollapse: ["responsive"],
    borderColor: ["responsive", "hover", "focus"],
    borderOpacity: ["responsive", "hover", "focus"],
    borderRadius: ["responsive"],
    borderStyle: ["responsive"],
    borderWidth: ["responsive"],
    boxShadow: ["responsive", "hover", "focus", "active"],
    boxSizing: ["responsive"],
    container: ["responsive"],
    cursor: ["responsive"],
    display: ["responsive"],
    divideColor: ["responsive"],
    divideOpacity: ["responsive"],
    divideStyle: ["responsive"],
    divideWidth: ["responsive"],
    fill: ["responsive"],
    flex: ["responsive"],
    flexDirection: ["responsive"],
    flexGrow: ["responsive"],
    flexShrink: ["responsive"],
    flexWrap: ["responsive"],
    float: ["responsive"],
    clear: ["responsive"],
    fontFamily: ["responsive"],
    fontSize: ["responsive"],
    fontSmoothing: ["responsive"],
    fontVariantNumeric: ["responsive"],
    fontStyle: ["responsive"],
    fontWeight: ["responsive", "hover", "focus"],
    height: ["responsive"],
    inset: ["responsive"],
    justifyContent: ["responsive"],
    justifyItems: ["responsive"],
    justifySelf: ["responsive"],
    letterSpacing: ["responsive"],
    lineHeight: ["responsive"],
    listStylePosition: ["responsive"],
    listStyleType: ["responsive"],
    margin: ["responsive"],
    maxHeight: ["responsive"],
    maxWidth: ["responsive"],
    minHeight: ["responsive"],
    minWidth: ["responsive"],
    objectFit: ["responsive"],
    objectPosition: ["responsive"],
    opacity: ["responsive", "hover", "focus"],
    order: ["responsive"],
    outline: ["responsive", "focus"],
    overflow: ["responsive"],
    overscrollBehavior: ["responsive"],
    padding: ["responsive"],
    placeContent: ["responsive"],
    placeItems: ["responsive"],
    placeSelf: ["responsive"],
    placeholderColor: ["responsive", "focus"],
    placeholderOpacity: ["responsive", "focus"],
    pointerEvents: ["responsive"],
    position: ["responsive"],
    resize: ["responsive"],
    space: ["responsive"],
    stroke: ["responsive"],
    strokeWidth: ["responsive"],
    tableLayout: ["responsive"],
    textAlign: ["responsive"],
    textColor: ["responsive", "hover", "focus"],
    textOpacity: ["responsive", "hover", "focus"],
    textDecoration: ["responsive", "hover", "focus"],
    textTransform: ["responsive"],
    userSelect: ["responsive"],
    verticalAlign: ["responsive"],
    visibility: ["responsive"],
    whitespace: ["responsive"],
    width: ["responsive"],
    wordBreak: ["responsive"],
    zIndex: ["responsive"],
    gap: ["responsive"],
    gridAutoFlow: ["responsive"],
    gridTemplateColumns: ["responsive"],
    gridAutoColumns: ["responsive"],
    gridColumn: ["responsive"],
    gridColumnStart: ["responsive"],
    gridColumnEnd: ["responsive"],
    gridTemplateRows: ["responsive"],
    gridAutoRows: ["responsive"],
    gridRow: ["responsive"],
    gridRowStart: ["responsive"],
    gridRowEnd: ["responsive"],
    transform: ["responsive"],
    transformOrigin: ["responsive"],
    scale: ["responsive", "hover", "focus"],
    rotate: ["responsive", "hover", "focus"],
    translate: ["responsive", "hover", "focus"],
    skew: ["responsive", "hover", "focus"],
    transitionProperty: ["responsive"],
    transitionTimingFunction: ["responsive"],
    transitionDuration: ["responsive"],
    transitionDelay: ["responsive"],
    animation: ["responsive"]
  },
  corePlugins: [
    "preflight",
    "container",
    "space",
    "divideWidth",
    "divideColor",
    "divideStyle",
    "divideOpacity",
    "accessibility",
    "appearance",
    "backgroundAttachment",
    "backgroundClip",
    "backgroundColor",
    "backgroundImage",
    "gradientColorStops",
    "backgroundOpacity",
    "backgroundPosition",
    "backgroundRepeat",
    "backgroundSize",
    "borderCollapse",
    "borderColor",
    "borderOpacity",
    "borderRadius",
    "borderStyle",
    "borderWidth",
    "boxSizing",
    "cursor",
    "display",
    "flexDirection",
    "flexWrap",
    "placeItems",
    "placeContent",
    "placeSelf",
    "alignItems",
    "alignContent",
    "alignSelf",
    "justifyItems",
    "justifyContent",
    "justifySelf",
    "flex",
    "flexGrow",
    "flexShrink",
    "order",
    "float",
    "clear",
    "fontFamily",
    "fontWeight",
    "height",
    "fontSize",
    "lineHeight",
    "listStylePosition",
    "listStyleType",
    "margin",
    "maxHeight",
    "maxWidth",
    "minHeight",
    "minWidth",
    "objectFit",
    "objectPosition",
    "opacity",
    "outline",
    "overflow",
    "overscrollBehavior",
    "padding",
    "placeholderColor",
    "placeholderOpacity",
    "pointerEvents",
    "position",
    "inset",
    "resize",
    "boxShadow",
    "fill",
    "stroke",
    "strokeWidth",
    "tableLayout",
    "textAlign",
    "textColor",
    "textOpacity",
    "fontStyle",
    "textTransform",
    "textDecoration",
    "fontSmoothing",
    "fontVariantNumeric",
    "letterSpacing",
    "userSelect",
    "verticalAlign",
    "visibility",
    "whitespace",
    "wordBreak",
    "width",
    "zIndex",
    "gap",
    "gridAutoFlow",
    "gridTemplateColumns",
    "gridAutoColumns",
    "gridColumn",
    "gridColumnStart",
    "gridColumnEnd",
    "gridTemplateRows",
    "gridAutoRows",
    "gridRow",
    "gridRowStart",
    "gridRowEnd",
    "transform",
    "transformOrigin",
    "scale",
    "rotate",
    "translate",
    "skew",
    "transitionProperty",
    "transitionTimingFunction",
    "transitionDuration",
    "transitionDelay",
    "animation"
  ],
  future: { removeDeprecatedGapUtilities: true },
  purge: [],
  target: "relaxed",
  prefix: "",
  important: false,
  separator: ":",
  presets: []
};
