name: Sync Issue to Monday.com
description: Syncs a new issue or specific issue changes to Monday.com tasks.

inputs:
  monday_key:
    description: The API key for Monday.com (set as a secret in the repository)
    required: true
  monday_board:
    description: The ID of the Monday.com board to sync with (set as a secret in the repository)
    required: true

runs:
  using: composite
  steps:
    - name: "Create Task"
      if: github.event.action == 'opened' ||
        (github.event.action == 'labeled' && github.event.label.name == 'monday.com sync')
      uses: actions/github-script@v8
      env:
        MONDAY_KEY: ${{ inputs.monday_key }}
        MONDAY_BOARD: ${{ inputs.monday_board }}
      with:
        script: |
          core.startGroup("Selected action: Create Task");
          const action = require('${{ github.action_path }}/../../scripts/monday/createTask.js')
          await action({github, context, core})
          core.endGroup();

    - name: "Update Label on Task"
      if: github.event.action == 'labeled' && github.event.label.name != 'monday.com sync'
      uses: actions/github-script@v8
      env:
        MONDAY_KEY: ${{ inputs.monday_key }}
        MONDAY_BOARD: ${{ inputs.monday_board }}
      with:
        script: |
          core.startGroup("Selected action: Update Label on Task");
          core.notice("Selected action: Update Label on Task");
          const action = require('${{ github.action_path }}/../../scripts/monday/updateLabels.js')
          await action({github, context, core})
          core.endGroup();

    - name: "Remove Label from Task"
      if: github.event.action == 'unlabeled'
      uses: actions/github-script@v8
      env:
        MONDAY_KEY: ${{ inputs.monday_key }}
        MONDAY_BOARD: ${{ inputs.monday_board }}
      with:
        script: |
          const action = require('${{ github.action_path }}/../../scripts/monday/removeLabel.js')
          await action({github, context, core})

    - name: "Update Milestone"
      if: github.event.action == 'milestoned' || github.event.action == 'demilestoned'
      uses: actions/github-script@v8
      env:
        MONDAY_KEY: ${{ inputs.monday_key }}
        MONDAY_BOARD: ${{ inputs.monday_board }}
      with:
        script: |
          const action = require('${{ github.action_path }}/../../scripts/monday/updateMilestone.js')
          await action({github, context, core})

    - name: "Update Task Title"
      if: github.event.action == 'edited'
      uses: actions/github-script@v8
      env:
        MONDAY_KEY: ${{ inputs.monday_key }}
        MONDAY_BOARD: ${{ inputs.monday_board }}
      with:
        script: |
          const action = require('${{ github.action_path }}/../../scripts/monday/updateTitle.js')
          await action({github, context, core})

    - name: "Update Task Assignee"
      if: github.event.action == 'assigned' || github.event.action == 'unassigned'
      uses: actions/github-script@v8
      env:
        MONDAY_KEY: ${{ inputs.monday_key }}
        MONDAY_BOARD: ${{ inputs.monday_board }}
      with:
        script: |
          const action = require('${{ github.action_path }}/../../scripts/monday/updateAssignee.js')
          await action({github, context, core})

    - name: "Update Task Status"
      if: github.event.action == 'closed' || github.event.action == 'reopened'
      uses: actions/github-script@v8
      env:
        MONDAY_KEY: ${{ inputs.monday_key }}
        MONDAY_BOARD: ${{ inputs.monday_board }}
      with:
        script: |
          const action = require('${{ github.action_path }}/../../scripts/monday/updateState.js')
          await action({github, context, core})

    - name: "Sync Action Changes"
      if: github.event.inputs.event_type == 'SyncActionChanges'
      uses: actions/github-script@v8
      env:
        MONDAY_KEY: ${{ inputs.monday_key }}
        MONDAY_BOARD: ${{ inputs.monday_board }}
      with:
        script: |
          const action = require('${{ github.action_path }}/../../scripts/monday/syncActionChanges.js')
          await action({github, context, core})
