version: 1
labels:
  - label: "enhancement"
    title: "^[fF][eE][aA][tT].*"
  - label: "bug"
    title: "^[fF][iI][xX].*"
  - label: "chore"
    title: "^[cC][hH][oO][rR][eE].*"
  - label: "chore"
    title: "^[bB][uU][iI][lL][dD].*"
  - label: "docs"
    title: "^[dD][oO][cC][sS].*"
  - label: "testing"
    title: "^[tT][eE][sS][tT].*"
  - label: "refactor"
    title: "^[rR][eE][fF][aA][cC][tT][oO][rR].*"
  - label: "tooling"
    title: "[tT][oO][oO][lL][iI][nN][gG].*"
