labelToAdd: 'need more info'
labelsToCheck:
  - bug
commentHeader: 'More information is required to proceed with this issue:'
requiredItems:
  -
    response: '- Copy the [issue template](https://github.com/Esri/calcite-components/issues/new?assignees=&labels=bug%2C+0+-+new%2C+needs+triage&template=bug.md&title=Bug%3A+) format and paste it into a comment, providing all of the requested items'
    requireAll: true
    content:
      - '### Actual Behavior'
      - '### Expected Behavior'
      - '### Reproduction Steps and Sample'
      - '### Relevant Info'
  -
    response: '- Provide a [codepen](https://codepen.io/pen), [codesandbox](https://codesandbox.io/s), or [jsbin](https://jsbin.com) that reproduces the issue'
    requireAll: false
    content:
      - 'https://jsbin.com/'
      - 'https://codepen.io/'
      - 'https://codesandbox.io/'
commentFooter: 'This issue will be automatically closed in three days if the information is not provided. Thanks for your understanding.'