#!/usr/bin/env bash

if [ "$BRANCH" = "dev" ]; then
    if [ "$NEXT_RELEASE_ENABLED" != "true" ]; then
        echo "Next release is disabled"
        exit 0
    fi

    if ! npm run util:is-next-deployable; then
        echo "No deployable changes in dev"
        exit 0
    fi
fi

npm install

# version the packages with lerna before building to ensure the version in
# Calcite components' source code preamble is correct for deployment
if [ "$BRANCH" = "dev" ]; then
    npm run version:next
elif [ "$BRANCH" = "main" ]; then
    npm run version:hotfix
elif [ "$BRANCH" = "rc" ]; then
    npm run version:rc
fi

npm run build
npm test

git config --global user.email "github-actions[bot]@users.noreply.github.com"
git config --global user.name "github-actions[bot]"

# make sure the committed, autogenerated files are up to date before releasing.
# The "|| true" prevents failure if there are no changes.
git add packages/calcite-components/src/components.d.ts package-lock.json || true
git commit -m "build: update types and package-lock" || true

# try deploying storybook, but still release next if it fails with "|| true"
if [ "$BRANCH" = "main" ]; then
    { npm run --workspace=@esri/calcite-components build-storybook &&
        npx --workspace=@esri/calcite-components storybook-to-ghpages \
            --host-token-env-variable=GH_TOKEN_FOR_STORYBOOK \
            --existing-output-dir=docs --ci; } || true

    # remove the built docs after storybook deploys to gh-pages
    git reset --hard
fi

if [ "$BRANCH" = "main" ]; then
    npm run publish:next
elif [ "$BRANCH" = "dev" ]; then
    npm run publish:hotfix
elif [ "$BRANCH" = "rc" ]; then
    npm run publish:rc
fi

npm run util:push-tags
