import { getAssetPath } from "@stencil/core";

export const CSS = {
  toggleIcon: "toggle-icon"
};

// some bundlers (e.g., Webpack) need dynamic import paths to be static
export const supportedDayJsLocaleToLocaleConfigImport = new Map([
  ["ar", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/ar.js`))],
  ["bg", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/bg.js`))],
  ["bs", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/bs.js`))],
  ["ca", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/ca.js`))],
  ["cs", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/cs.js`))],
  ["da", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/da.js`))],
  ["de", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/de.js`))],
  ["de-at", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/de-at.js`))],
  ["de-ch", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/de-ch.js`))],
  ["el", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/el.js`))],
  ["en", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/en.js`))],
  ["en-au", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/en-au.js`))],
  ["en-ca", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/en-ca.js`))],
  ["en-gb", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/en-gb.js`))],
  ["es", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/es.js`))],
  ["es-mx", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/es-mx.js`))],
  ["et", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/et.js`))],
  ["fi", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/fi.js`))],
  ["fr", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/fr.js`))],
  ["fr-ch", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/fr-ch.js`))],
  ["he", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/he.js`))],
  ["hi", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/hi.js`))],
  ["hr", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/hr.js`))],
  ["hu", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/hu.js`))],
  ["id", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/id.js`))],
  ["it", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/it.js`))],
  ["it-ch", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/it-ch.js`))],
  ["ja", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/ja.js`))],
  ["ko", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/ko.js`))],
  ["lt", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/lt.js`))],
  ["lv", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/lv.js`))],
  ["mk", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/mk.js`))],
  ["no", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/no.js`))],
  ["nl", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/nl.js`))],
  ["pl", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/pl.js`))],
  ["pt", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/pt.js`))],
  ["pt-pt", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/pt-pt.js`))],
  ["ro", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/ro.js`))],
  ["ru", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/ru.js`))],
  ["sk", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/sk.js`))],
  ["sl", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/sl.js`))],
  ["sr", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/sr.js`))],
  ["sv", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/sv.js`))],
  ["th", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/th.js`))],
  ["tr", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/tr.js`))],
  ["uk", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/uk.js`))],
  ["vi", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/vi.js`))],
  ["zh-cn", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/zh-cn.js`))],
  ["zh-hk", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/zh-hk.js`))],
  ["zh-tw", () => import(getAssetPath(`./assets/input-time-picker/nls/dayjs/locale/zh-tw.js`))]
]);
