/**
 * This file is autogenerated by `@arcgis/lumina-compiler` - do not edit it manually.
 * Manual edits will be overwritten.
 *
 * This file provides JSX types for the component libraries your package uses.
 *
 * If you need to provide additional types, create a separate file.
 */
/// <reference types="@arcgis/lumina/globalTypes" />
/// <reference types="vitest/config" />
/// <reference types="vitest/browser" />
