name: Bug
description: Report a bug in a component
labels: ["bug", "0 - new", "needs triage"]
body:
  - type: checkboxes
    id: existing-issues
    attributes:
      label: Check existing issues
      description: If someone has already opened an issue for what you are experiencing, please add a 👍 reaction to the existing issue instead of creating a new one. For support, please check the [community forum](https://developers.arcgis.com/calcite-design-system/community/).
      options:
        - label: I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear description of the issue (optionally include before/after screenshots/GIFs).
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected instead, and why?
    validations:
      required: true
  - type: input
    id: sample
    attributes:
      label: Reproduction Sample
      description: |
        We provide the following templates to help get started: [codepen](https://codepen.io/pen?template=RwgrjEx) (just Calcite), [React Codesandbox](https://codesandbox.io/s/calcite-template-p95kp?file=/src/App.js) (Calcite with React wrapper), [Angular Codesandbox](https://codesandbox.io/p/sandbox/little-fire-2hx4qh?file=%2Fsrc%2Fapp%2Fapp.component.html%3A16%2C51), or [jsbin](https://jsbin.com/qecewik/edit?html,output) (Calcite with ArcGIS JSAPI). You can also make your own sample using one of the those websites. Alternatively, a [documentation sample](https://developers.arcgis.com/calcite-design-system/components) can be used if the issue is reproducible. If you are experiencing build or Node related errors, please provide a GitHub repo for the sample.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: Clear, numbered steps for reproducing the issue using the sample provided above.
      placeholder: |
        1. Open the DevTools console
        2. Click on XYZ
        3. ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Reproduction Version
      description: The latest version that reproduces the issue.
    validations:
      required: true
  - type: textarea
    id: relevant
    attributes:
      label: Relevant Info
      description: Browser, OS, mobile, stack traces, related issues, suggestions/resources on how to fix, etc.
      placeholder: |
        Windows 10, Chrome 97
        `Uncaught TypeError: Cannot read property of undefined`
        ...
    validations:
      required: false
  - type: input
    id: regression
    attributes:
      label: Regression?
      description: Please provide the last working version if the issue is a regression.
    validations:
      required: false
  - type: dropdown
    id: priority-impact
    validations:
      required: true
    attributes:
      label: Priority impact
      multiple: false
      description: What is the impact to you, your team, or organization? Use discretion and only select "need" or "emergency" priorities for high user impact and quality issues. For instance, would someone notice, in a bad way, if this issue were present in the release?
      options:
        - p4 - not time sensitive
        - p3 - want for upcoming milestone
        - p2 - want for current milestone
        - p1 - need for current milestone
        - p0 - emergency
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: How does the issue effect your team, or your work? Can range from minor to blocking or prohibiting workflows. Helps Calcite Design System team members with prioritization.
    validations:
      required: false
  - type: checkboxes
    id: packages
    attributes:
      label: Calcite package
      description: Select the relevant [package(s)](https://github.com/Esri/calcite-design-system/tree/main/packages) related to the request.
      options:
        - label: "@esri/calcite-components"
        - label: "@esri/calcite-components-angular"
        - label: "@esri/calcite-components-react"
        - label: "@esri/calcite-design-tokens"
        - label: "@esri/eslint-plugin-calcite-components"
    validations:
      required: false
  - type: dropdown
    id: esri-team
    validations:
      required: true
    attributes:
      label: Esri team
      multiple: false
      description: If you work at Esri, please select your product team. Otherwise choose "N/A". If your team is not listed, choose "N/A", and then edit the line after submitting the issue.
      options:
        - N/A
        - ArcGIS Solutions
        - ArcGIS AppStudio
        - ArcGIS Business/Community Analyst
        - ArcGIS Charts
        - ArcGIS Dashboards
        - ArcGIS Developer Experience
        - ArcGIS Enterprise
        - ArcGIS Excalibur
        - ArcGIS Experience Builder
        - ArcGIS Field Apps
        - ArcGIS GeoAnalytics
        - ArcGIS GeoBIM
        - ArcGIS GeoPlanner
        - ArcGIS Hub
        - ArcGIS Indoors
        - ArcGIS Insights
        - ArcGIS Instant Apps
        - ArcGIS Knowledge
        - ArcGIS Living Atlas
        - ArcGIS Map Viewer
        - ArcGIS Marketplace
        - ArcGIS Mission
        - ArcGIS Monitor
        - ArcGIS Network Analyst
        - ArcGIS Online
        - ArcGIS Pro
        - ArcGIS Maps SDK for JavaScript
        - ArcGIS Scene Viewer
        - ArcGIS Site Scan
        - ArcGIS StoryMaps
        - ArcGIS Survey123
        - ArcGIS Web Analysis
        - ArcGIS Urban
        - Esri Marketing
        - Professional Services - Midwest Delivery Center
        - Professional Services - Services Delivery
        - Calcite (design)
        - Calcite (dev)
