name: Documentation
description: Report issues with documentation
labels: ["docs", "0 - new", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        - Please [check for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates. If someone has already opened an issue for what you are experiencing, please add a 👍 reaction to the existing issue instead of creating a new one.
        - For support, please check the [community forum](https://developers.arcgis.com/calcite-design-system/community/).
  - type: dropdown
    id: component
    validations:
      required: true
    attributes:
      label: Which Component
      description: Which component(s) are related to this issue? (Select all that apply).
      multiple: true
      default: 0
      options:
        - N/A
        - Unknown / Not Sure
        - Accordion
        - Accordion Item
        - Action
        - Action Bar
        - Action Group
        - Action Pad
        - Alert
        - Autocomplete
        - Autocomplete Item
        - Autocomplete Item Group
        - Avatar
        - Block
        - Block Group
        - Block Section
        - Button
        - Card
        - Card Group
        - Carousel
        - Carousel Item
        - Checkbox
        - Chip
        - Chip Group
        - Color Picker
        - Combobox
        - Combobox Item
        - Combobox Item Group
        - Date Picker
        - Dialog
        - Dropdown
        - Dropdown Group
        - Dropdown Item
        - Fab
        - Filter
        - Flow
        - Flow Item
        - Icon
        - Inline Editable
        - Input
        - Input Date Picker
        - Input Message
        - Input Number
        - Input Text
        - Input Time Picker
        - Input Time Zone
        - Label
        - Link
        - List
        - List Item
        - List Item Group
        - Loader
        - Menu
        - Menu Item
        - Meter
        - Modal
        - Navigation
        - Navigation Logo
        - Navigation User
        - Notice
        - Option
        - Option Group
        - Pagination
        - Panel
        - Popover
        - Progress
        - Radio Button
        - Radio Button Group
        - Rating
        - Scrim
        - Segmented Control
        - Segmented Control Item
        - Select
        - Sheet
        - Shell
        - Shell Center Row
        - Shell Panel
        - Slider
        - Split Button
        - Stepper
        - Stepper Item
        - Swatch
        - Swatch Group
        - Switch
        - Tab
        - Tab Nav
        - Tab Title
        - Table
        - Table Cell
        - Table Header
        - Table Row
        - Tabs
        - Text Area
        - Tile
        - Tile Group
        - Tile Select
        - Tile Select Group
        - Time Picker
        - Tip
        - Tip Group
        - Tip Manager
        - Tooltip
        - Tree
        - Tree Item
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be added or fixed?
    validations:
      required: true
  - type: textarea
    id: resources
    attributes:
      label: Resources
      description: Any other helpful information, including examples or suggestions.
    validations:
      required: false
