export type Strings = {
  b: string;
  blue: string;
  deleteColor: string;
  g: string;
  green: string;
  h: string;
  hsv: string;
  hex: string;
  hue: string;
  noColor: string;
  r: string;
  red: string;
  rgb: string;
  s: string;
  saturation: string;
  saveColor: string;
  saved: string;
  v: string;
  value: string;
};
