// @ts-nocheck
@Component({ tag: "sample-tag" })
export class SampleTag {
  render() {
    return (
      <Host>
        <div
          class="some-class"
          id="element"
          onClick={() => {
            /* click! */
          }}
          tabIndex={0}
          // eslint-disable-next-line enforce-ref-last-prop -- auto-generated by @esri/calcite-components/enforce-ref-last-prop
          ref={(el: HTMLDivElement): void => {
            /* refEl */
          }}
        >
          test Note: we are intentionally specifying `enforce-ref-last-prop` in the disable line as
          RuleTester can't be configured with multiple rules and this does not disable the custom
          rule, please see the output file for the correctly generated disable line
        </div>
      </Host>
    );
  }
}
