export const CSS = {
  container: "container",
  containerRange: "container--range",
  graph: "graph",
  handle: "handle",
  handleExtension: "handle-extension",
  handleLabel: "handle__label",
  handleLabelMinValue: "handle__label--minValue",
  handleLabelValue: "handle__label--value",
  handleLabelVertical: "handle__label--vertical",
  handleLabelVerticalReversed: "handle__label--vertical-reversed",
  hyphen: "hyphen",
  hyphenWrap: "hyphen--wrap",
  static: "static",
  thumb: "thumb",
  thumbActive: "thumb--active",
  thumbContainer: "thumb-container",
  thumbMinValue: "thumb--minValue",
  thumbPrecise: "thumb--precise",
  thumbValue: "thumb--value",
  thumbVertical: "thumb--vertical",
  thumbVerticalReversed: "thumb--vertical-reversed",
  thumbHorizontalReversed: "thumb--horizontal-reversed",
  mirrored: "mirrored",
  tick: "tick",
  tickActive: "tick--active",
  tickLabel: "tick__label",
  tickLabelVertical: "tick__label--vertical",
  tickLabelVerticalReversed: "tick__label--vertical-reversed",
  tickLabelHorizontalReversed: "tick__label--horizontal-reversed",
  tickMax: "tick__label--max",
  tickMin: "tick__label--min",
  ticks: "ticks",
  track: "track",
  trackRange: "track__range",
  transformed: "transformed",
  trackVertical: "track--vertical",
};

export const maxTickElementThreshold = 250;
