export const CSS = {
  bottomLeft: "bottom-left",
  bottomRight: "bottom-right",
  button: "button",
  delimiter: "delimiter",
  hour: "hour",
  hourDown: "hour-down",
  hourUp: "hour-up",
  input: "input",
  meridiem: "meridiem",
  meridiemDown: "meridiem-down",
  meridiemUp: "meridiem-up",
  minute: "minute",
  minuteDown: "minute-down",
  minuteUp: "minute-up",
  second: "second",
  secondDown: "second-down",
  secondUp: "second-up",
  timePicker: "time-picker",
  topLeft: "top-left",
  topRight: "top-right"
};

export const TEXT = {
  intlHour: "Hour",
  intlHourDown: "Decrease hour",
  intlHourUp: "Increase hour",
  intlMeridiem: "AM/PM",
  intlMeridiemDown: "Decrease AM/PM",
  intlMeridiemUp: "Increase AM/PM",
  intlMinute: "Minute",
  intlMinuteDown: "Decrease minute",
  intlMinuteUp: "Increase minute",
  intlSecond: "Second",
  intlSecondDown: "Decrease second",
  intlSecondUp: "Increase second",
}