name: Build Storybook
description: Install dependencies and build Storybook output

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        cache: true
    - uses: actions/setup-node@v6
      with:
        node-version-file: package.json

    - shell: bash
      env:
        STORYBOOK_SCREENSHOT_TEST_BUILD: true
      run: |
        pnpm install
        pnpm --filter @esri/calcite-design-tokens build
        pnpm --filter @esri//calcite-tailwind-preset build
        pnpm --filter @esri/calcite-ui-icons build
        pnpm --filter @esri/calcite-components build-storybook
