export const CSS = {
  checked: "checked",
  description: "description",
  descriptionOnly: "description-only",
  disabled: "disabled",
  heading: "heading",
  headingOnly: "heading-only",
  icon: "icon",
  iconOnly: "icon-only",
  inputAlignmentEnd: "input-alignment-end",
  inputAlignmentStart: "input-alignment-start",
  inputEnabled: "input-enabled",
  largeVisual: "large-visual",
  tile: "tile",
  tileContentContainer: "tile-content-container",
  tileContent: "tile-content",
  tileDescription: "tile-description",
  tileHeading: "tile-heading",
  tileLargeVisual: "tile--large-visual",
  widthAuto: "width-auto",
  widthFull: "width-full",
};
