export const CSS = {
  meter: "meter",
  meterFill: "meter-fill",
  meterStepLine: "meter-step-line",
  meterLabel: "meter-label",
  meterLabelContainer: "meter-label-container",
  meterLabelRange: "meter-label-range",
  meterLabelValue: "meter-label-value",
  meterUnitLabel: "meter-unit-label",
  meterStepsVisible: "meter-steps-visible",
  meterValueVisible: "meter-value-visible",
  success: "success",
  warning: "warning",
  danger: "danger",
};
