import type { CamelCaseIcon, KebabCaseIcon } from "@esri/calcite-ui-icons";
import type { KebabCase } from "type-fest";

type Digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9";

type ContainsNumber<T extends string> = Extract<T, `${string}${Digit}${string}`>;

/**
 * This redundant type avoids breaking change from invalid icon names generated by the previous type that worked at runtime
 *
 * @deprecated in v5.2.0, removal target v7.0.0. Use the `KebabCaseIcon` or `CamelCaseIcon` types instead.
 */
type LegacyKebabCaseIcon = KebabCase<ContainsNumber<CamelCaseIcon>>;

export type IconName = LegacyKebabCaseIcon | KebabCaseIcon | CamelCaseIcon;
