export const CSS = {
  container: "container",
  containerRange: "container--range",
  graph: "graph",
  handle: "handle",
  handleExtension: "handle-extension",
  handleLabel: "handle__label",
  handleLabelMinValue: "handle__label--minValue",
  handleLabelValue: "handle__label--value",
  hyphen: "hyphen",
  static: "static",
  thumb: "thumb",
  thumbActive: "thumb--active",
  thumbMinValue: "thumb--minValue",
  thumbPrecise: "thumb--precise",
  thumbValue: "thumb--value",
  tick: "tick",
  tickActive: "tick--active",
  tickLabel: "tick__label",
  tickLabelMin: "tick__label--min",
  tickLabelMax: "tick__label--max",
  ticks: "ticks",
  track: "track",
  trackRange: "track__range",
  transformed: "transformed"
};
