#!/usr/bin/env sh

if ! bash -c ': >/dev/tty'; then
    exit 0
fi

current_branch="$(git rev-parse --abbrev-ref HEAD)"

case "$current_branch" in
    dev | main | rc)
        printf "You're about to push a protected branch, is that what you intended? [y|n] "
        read -r response

        case "$response" in
            y | Y) exit 0 ;;
            *) exit 1 ;;
        esac
        ;;
    *) exit 0 ;;
esac
