#!/usr/bin/env sh

check_ui_icon_name_consistency() {
  # this pattern checks for `<iconName>-<size>.svg` or `<iconName>-<size>-f.svg` for filled icons
  # where `<iconName>` is kebab-case, `<size>` is 16, 24, or 32
  valid_pattern="^[a-z0-9-]+-(16|24|32)(-f)?\\.svg$"

  # this pattern will check for invalid use of "-f-" anywhere except right before the size
  invalid_pattern="\-[a-z0-9]+-f-"

  staged_files="$(
    git diff --cached --name-only --diff-filter=ACM | grep -E "packages/calcite-ui-icons/icons/.*\.svg" || true
  )"

  if [ -n "$staged_files" ]; then
    for file in $staged_files; do
      filename="$(basename "$file")"

      # first, ensure the filename follows the valid pattern
      if ! echo "$filename" | grep -qE "$valid_pattern"; then
        printf "%s\n%s" \
          "error: file '$file' does not follow the naming convention:" \
          "(<iconname>-<size>.svg | <iconname>-<size>-f.svg)"
        exit 1
      fi

      # then, ensure there's no invalid use of "-f-" anywhere except right before the size
      if echo "$filename" | grep -qE "$invalid_pattern"; then
        printf '%s\n%s' \
          "error: file '$file' has an invalid '-f-' and does not follow the naming convention:" \
          "(<iconname>-<size>.svg | <iconname>-<size>-f.svg)"
        exit 1
      fi
    done
  fi

  unset staged_files
}

npx tsx ./packages/calcite-components/support/updateT9nManifest.ts
lint-staged
check_ui_icon_name_consistency

exit 0
