#!/bin/bash
# from https://riptutorial.com/git/example/16164/pre-push

protected_branch='master'
current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ $protected_branch = $current_branch ] && [ exec < /dev/tty ]
then
    read -p "You're about to push master, is that what you intended? [y|n] " -n 1 -r < /dev/tty
    echo
    if echo $REPLY | grep -E '^[Yy]$' > /dev/null
    then
        exit 0
    fi
    exit 1
# disabled due to Windows error: https://github.com/Esri/calcite-components/pull/4307
# else
    # npm run util:check-squash-mergeable-branch
    # exit
fi