#!/bin/bash

# from https://riptutorial.com/git/example/16164/pre-push

protected_branch='master'
current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ $protected_branch = $current_branch ] && [ exec < /dev/tty ]
then
    read -p "You're about to push master, is that what you intended? [y|n] " -n 1 -r < /dev/tty
    echo
    if echo $REPLY | grep -E '^[Yy]$' > /dev/null
    then
        exit 0
    fi
    exit 1
else
    exit_code=1
    conventional_commit_regex='^((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(\w+\))?(!)?(: (.*\s*)*))'
    commit_messages=$(git log --format=%B $current_branch --not $protected_branch | tr '\n' ',')

    while [ "$commit_messages" != "$iteration" ]; do
        # extract the substring from start of string up to delimiter.
        iteration=${commit_messages%%,,*}
        # delete this first "element" AND next separator.
        commit_messages=${commit_messages#$iteration,,}
        # match conventional commit regex
        [[ "$iteration" =~ $conventional_commit_regex ]] && exit_code=0
    done
    [[ $exit_code -eq 1 ]] && printf "Error: please make a conventional commit\nhttps://github.com/Esri/calcite-components/blob/master/CONTRIBUTING.md#commit-message-format\n"
    exit $exit_code
fi