name: Add issue blocking relationships
on:
  issues:
    types: [opened, edited, closed, reopened, labeled, unlabeled, milestoned, demilestoned, assigned, unassigned]
  workflow_dispatch:
    inputs:
      issue_number:
        type: number
        description: "The target issue number for adding blocking relationships."
        required: true
jobs:
  add-blocking-relationships:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v6

      - name: "Adding blocking relationships from issue descriptions"
        uses: actions/github-script@v8
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/addBlockingRelationships.js')
            await action({github, context, core})
