name: Chromatic
on:
  pull_request:
    branches: [rc, dev]
    types: [opened, labeled, synchronize]
jobs:
  run:
    if: >
      github.event_name == 'pull_request' &&
      github.event.action == 'labeled' &&
      github.event.label.name == 'pr ready for visual snapshots' &&
      !contains(github.event.pull_request.labels.*.name, 'skip visual snapshots')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          cache: true
      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
      - name: Build storybook
        env:
          STORYBOOK_SCREENSHOT_TEST_BUILD: true
          CHROMATIC_DIFF_THRESHOLD: ${{ secrets.CHROMATIC_DIFF_THRESHOLD }}
        run: |
          pnpm install
          pnpm --filter @esri/calcite-design-tokens build
          pnpm --filter @esri/calcite-tailwind-preset build
          pnpm --filter @esri/calcite-ui-icons build
          pnpm --filter @esri/calcite-components build-storybook
      - name: Publish to Chromatic
        uses: chromaui/action@v13
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          zip: true
          exitOnceUploaded: true
          autoAcceptChanges: ${{ github.base_ref || github.ref_name }}
          workingDir: packages/components
          storybookBuildDir: docs
        env:
          STORYBOOK_SCREENSHOT_TEST_BUILD: true
          CHROMATIC_DIFF_THRESHOLD: ${{ secrets.CHROMATIC_DIFF_THRESHOLD }}
  skip:
    if: >
      github.event_name == 'pull_request' &&
      contains(github.event.pull_request.labels.*.name, 'skip visual snapshots')
    runs-on: ubuntu-latest
    steps:
      - name: Skip Chromatic
        uses: guibranco/github-status-action-v2@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: UI Tests
          description: Chromatic run skipped
          state: success
          sha: ${{ github.event.pull_request.head.sha || github.sha }}
