name: Chromatic

on:
  push:
    branches: [rc, dev]
  pull_request:
    branches: [rc, dev]
    types: [labeled]

jobs:
  run-pr:
    if: >
      github.event.label.name == 'pr ready for visual snapshots' &&
      !contains(github.event.pull_request.labels.*.name, 'skip visual snapshots')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: ./.github/actions/chromatic/build-storybook

      - uses: ./.github/actions/chromatic/publish
        with:
          project-token: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          auto-accept-changes: ${{ github.base_ref || github.ref_name }}
          working-dir: packages/components
          storybook-build-dir: docs
          chromatic-diff-threshold: ${{ secrets.CHROMATIC_DIFF_THRESHOLD }}
          chromatic-branch: ${{ github.event.pull_request.head.ref || github.ref_name }}
          chromatic-sha: ${{ github.event.pull_request.head.sha || github.ref }}
          chromatic-slug: ${{ github.repository }}

  run-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ./.github/actions/chromatic/build-storybook

      - uses: ./.github/actions/chromatic/publish
        with:
          project-token: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          auto-accept-changes: ${{ github.ref_name }}
          working-dir: packages/components
          storybook-build-dir: docs
          chromatic-diff-threshold: ${{ secrets.CHROMATIC_DIFF_THRESHOLD }}

  skip:
    if: contains(github.event.pull_request.labels.*.name, 'skip visual snapshots')
    runs-on: ubuntu-latest
    steps:
      - name: Skip Chromatic
        uses: guibranco/github-status-action-v2@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: UI Tests
          description: Chromatic run skipped
          state: success
          sha: ${{ github.event.pull_request.head.sha }}
