name: Add Issue Labels
on:
  issues:
    types: [opened, edited]
jobs:
  product-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add Esri Product Label
        uses: actions/github-script@v7
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/addEsriProductLabel.js')
            await action({github, context, core})

      - name: Add Calcite Package Label
        uses: actions/github-script@v7
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/addCalcitePackageLabel.js')
            await action({github, context, core})

      - name: Add Priority Label
        uses: actions/github-script@v7
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/addPriorityLabel.js')
            await action({github, context, core})

      - name: Add Regression Label
        uses: actions/github-script@v7
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/addRegressionLabel.js')
            await action({github, context, core})
