name: Issue Notifications
on:
  issues:
    types: [labeled]
jobs:
  determine-action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: "Assign for verification"
        if: github.event.label.name == '3 - installed'
        uses: actions/github-script@v7
        env:
          ISSUE_VERIFIERS: ${{secrets.ISSUE_VERIFIERS}}
          CALCITE_DESIGNERS: ${{secrets.CALCITE_DESIGNERS}}
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/assignForVerification.js')
            await action({github, context, core})

      - name: "Spike complete notification"
        if: github.event.label.name == 'spike complete'
        uses: actions/github-script@v7
        env:
          MANAGERS: ${{secrets.CALCITE_MANAGERS}}
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/notifyWhenSpikeComplete.js')
            await action({github, context, core})

      - name: "Ready for dev notification"
        if: github.event.label.name == 'ready for dev'
        uses: actions/github-script@v7
        env:
          MANAGERS: ${{secrets.CALCITE_MANAGERS}}
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/notifyWhenReadyForDev.js')
            await action({github, context, core})

      - name: "New component notification"
        if: github.event.label.name == 'new component'
        uses: actions/github-script@v7
        env:
          DESIGNERS: ${{secrets.CALCITE_DESIGNERS}}
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/notifyAboutNewComponent.js')
            await action({github, context, core})
