name: Issue Notifications
on:
  issues:
    types: [labeled]
jobs:
  determine-action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      actions: write
    steps:
      - uses: actions/checkout@v6

      - name: "Installed notification"
        if: github.event.label.name == '4 - installed'
        uses: actions/github-script@v9
        env:
          ISSUE_VERIFIERS: ${{secrets.ISSUE_VERIFIERS}}
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/notifyWhenInstalled.cjs')
            await action({github, context, core})

      - name: "Spike complete notification"
        if: github.event.label.name == 'spike complete'
        uses: actions/github-script@v9
        env:
          PLANNERS: ${{secrets.CALCITE_PLANNERS}}
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/notifyWhenSpikeComplete.cjs')
            await action({github, context, core})

      - name: "Ready for dev notification"
        if: github.event.label.name == '2 - ready for dev'
        uses: actions/github-script@v9
        env:
          PLANNERS: ${{secrets.CALCITE_PLANNERS}}
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/notifyWhenReadyForDev.cjs')
            await action({github, context, core})

      - name: "New component notification"
        if: github.event.label.name == 'new component'
        uses: actions/github-script@v9
        env:
          DESIGNERS: ${{secrets.CALCITE_DESIGNERS}}
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/notifyAboutNewComponent.cjs')
            await action({github, context, core})

      - name: "Icon request notification"
        if: github.event.label.name == 'calcite-ui-icons'
        uses: ./.github/actions/notify-new-icon
        with:
          webhook: ${{ secrets.TEAMS_ICON_WEBHOOK_URI }}
