name: Update Issue Metadata
on:
  issues:
    types: [opened, edited]
jobs:
  product-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      actions: write
    steps:
      - uses: actions/checkout@v6

      - name: Add Esri Product Label
        uses: actions/github-script@v9
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/addEsriProductLabel')
            await action({github, context, core})

      - name: Add Calcite Package Label
        uses: actions/github-script@v9
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/addCalcitePackageLabel')
            await action({github, context, core})

      - name: Add Priority Label
        uses: actions/github-script@v9
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/addPriorityLabel')
            await action({github, context, core})

      - name: Add Regression Label
        uses: actions/github-script@v9
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/addRegressionLabel')
            await action({github, context, core})

      - name: Add Component Label
        uses: actions/github-script@v9
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/addComponentLabel')
            await action({github, context, core})

      - name: Add Issues To Backlog
        uses: actions/github-script@v9
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/addIssuesToBacklog')
            await action({github, context, core})
