name: PR T9n
on:
  pull_request:
    branches:
      - translations_dev
permissions:
  pull-requests: write
jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Assign Reviewer"
        uses: actions/github-script@v7
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/assignPullRequestReviewer.js')
            await action({github, context})
