on:
  push:
    branches:
      - "release-please--branches--releases/**"
permissions:
  contents: write
  pull-requests: write
name: clean-changelog
jobs:
  clean-changelog:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
          fetch-depth: 0
      - name: Set pnpm + Node
        uses: pnpm/setup@v3
        with:
          cache: true
          install: false
      - name: Remove Next Changelog Entries
        run: |
          git pull
          pnpm install
          pnpm util:remove-prerelease-changelog-entries
      - name: Push Changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -am "docs: remove prerelease changelog entries" || true
          git push origin ${{ github.ref_name }}
